config/routes.rb
Rails.application.routes.draw do
  get 'report/index'
  patch 'report/:id' => 'report#update'

  get 'welcome/index'

  root 'welcome#index'

end

app/models/premium_subscription.rb
# == Schema Information
#
# Table name: premium_subscriptions
#
#  id                  :integer          not null, primary key
#  shirt_size          :integer
#  user_id             :integer
#  subscription_length :integer
#  status              :integer          default(0)
#  shipping_addres     :text
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

class PremiumSubscription < ActiveRecord::Base
  validates :shirt_size, :user, :subscription_length, presence: true
  belongs_to :user

  scope :between, ->(from, to) { where("created_at >= ?", from.to_date.beginning_of_day).where("created_at <= ?", to.to_date.end_of_day) }

  enum shirt_size: ["s", "m", "l", "xl", "xxl"]
  def shirt_size_enum
    self.class.shirt_sizes.to_a
  end

  enum subscription_length: ["1 week", "1 month", "1 year"]
  def subscription_length_enum
    self.class.subscription_lengths.to_a
  end

  enum status: ["unshipped", "shipped"]
  def status_enum
    self.class.statuses.to_a
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  first_name :string
#  last_name  :string
#  username   :string
#  uid        :string
#  provider   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  # forgot password field.
  validates :first_name, :username, presence: true

  has_one :premium_subscription, :dependent => :destroy

  # this method return true if user is subscribed, and false otherwise.
  def subscribed
    premium_subscription.present?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/report_controller.rb
class ReportController < ApplicationController
  def index

    if validate_date(params[:from_date]) and validate_date(params[:to_date])
      @premium_subscription = PremiumSubscription.between(params[:from_date], params[:to_date]).order(status: :desc)
    else
      @premium_subscription = PremiumSubscription.all.order(status: :desc)
    end

    respond_to do |format|
      format.html 
      format.xlsx {
        response.headers['Content-Disposition'] = 'attachment; filename="report.xlsx"'
      }
    end
  end

  def update
    premium_subscription = PremiumSubscription.find(params[:id])
    premium_subscription[:status] = 1 - premium_subscription[:status]

    respond_to do |format|
      if premium_subscription.save
        format.json { render json: {subscription_status: premium_subscription.status}, status: :created}
      else
        format.json { render json: premium_subscription.errors, status: :unprocessable_entity }
      end
    end
  end

private
  
  def validate_date(date)
    date.present? and /\d{4}\-\d{2}\-\d{2}/.match(date).present?
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TshirtShipped</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Fishing Company</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home <span class="sr-only">(current)</span></a></li>
        <li><%= link_to "Report", report_index_path  %></li>
      </ul>
      <%= form_tag(report_index_path(format: :xlsx), method: "get", class: 'navbar-form navbar-left') do %>
        <div class="form-group">
          <input name="from_date" type="text" class="form-control" placeholder="From date (yyyy-mm-dd)">
          <input name="to_date" type="text" class="form-control" placeholder="To date (yyyy-mm-dd)">
        </div>
        <button type="submit" class="btn btn-default">Download</button>
      <% end %>
    </div>
  </div>
</nav>

<div class="container-fluid">
  <%= yield %>  
</div>


</body>
</html>

app/views/report/download.html.erb
<h1>Report#download</h1>
<p>Find me in app/views/report/download.html.erb</p>

app/views/report/index.html.erb
<h1>Report</h1>

<% if @premium_subscription.any? %>

<%= link_to 'Download all to .xlsx', report_index_path(format: :xlsx), class: 'btn btn-default' %>
<br>
<br>
  <table class="table">
    <tr>
      <th>Name</th>
      <th>T-Shirt size</th>
      <th>Status</th>
      <th>Subscription Length</th>
      <th>Date Subscribed</th>
    </tr>
  <% @premium_subscription.each do |subscription| %>
    <tr>
      <td><%= subscription.user.first_name %> <%= subscription.user.last_name %></td>
      <td><%= subscription.shirt_size %></td>
      <td><a href="javascript:updateSubscription(<%= subscription.id %>)" id="subs_<%= subscription.id %>"><%= subscription.status %></a></td>
      <td><%= subscription.subscription_length %></td>
      <td><%= subscription.created_at %></td>
    </tr>
  <% end %>
  </table>
<% end %>

<script type="text/javascript">
function updateSubscription(id){
  $.ajax({
    type: "PATCH",
    dataType: "json",
    url: '/report/'+id,
    success : function(json) {
      $("#subs_"+id).text(json.subscription_status)
      
    },
    error : function(xhr, status) {
        console.log(xhr)
    }
  })
}
</script>

app/views/welcome/index.html.erb
<h1>Fishing Company</h1>
<p>Welcome to <strong>Fishing Company</strong>. Subscribe and get a free bag of Swag.</p>

 